# Generated by Django 3.2.5 on 2021-08-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='преимущество')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Benefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=511, verbose_name='Заголовок')),
                ('descr', models.TextField(verbose_name='Описание')),
                ('benefit', models.ManyToManyField(to='blog.Benefit', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Список преимушеств',
                'verbose_name_plural': 'Списки преимуществ',
            },
        ),
        migrations.CreateModel(
            name='ElPartition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('img', models.ImageField(upload_to='static/images/elpartition', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='title')),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='ключевые слова')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес-страницы')),
                ('benefits', models.ManyToManyField(blank=True, related_name='benes', to='blog.Benefits', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Элемент раздела',
                'verbose_name_plural': 'Элементы раздела',
            },
        ),
        migrations.CreateModel(
            name='Partition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('cost', models.PositiveSmallIntegerField(default=0, verbose_name='Стоимость')),
                ('preview', models.ImageField(default='default.jpg', upload_to='static/images/preview', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='title')),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='ключевые слова')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес-страницы')),
            ],
            options={
                'verbose_name': 'Раздел Продукции',
                'verbose_name_plural': 'Разделы Продукции',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Площадь')),
                ('time', models.CharField(max_length=10, verbose_name='Время работы')),
                ('published', models.DateField(auto_now_add=True, verbose_name='Опубликовано')),
                ('img', models.ImageField(upload_to='static/images/products', verbose_name='Изображение')),
                ('telephone', models.SmallIntegerField(blank=True, null=True, verbose_name='Телефон клиента')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя клиента')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='title')),
                ('meta_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta description')),
                ('keywords', models.TextField(blank=True, null=True, verbose_name='ключевые слова')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес-страницы')),
                ('elem_partitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.elpartition', verbose_name='Элемент раздела')),
            ],
            options={
                'verbose_name': 'Выполненный заказ',
                'verbose_name_plural': 'Выполненные заказы',
                'ordering': ['-published'],
            },
        ),
        migrations.AddField(
            model_name='elpartition',
            name='partition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='blog.partition', verbose_name='Раздел'),
        ),
    ]
