# Generated by Django 3.2.6 on 2021-08-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_partition_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='declaration',
            field=models.TextField(default='', verbose_name='Большое описание'),
        ),
    ]
